In [12]:
import qutip
from qutip import Qobj,basis
from qutip import sigmax , sigmaz , sigmay
from qutip import tensor
from numpy.random import normal
import numpy as np

In [8]:
sigx = sigmax()
sigz = sigmaz()
sigy = sigmay()
iid = qutip.qeye(2)

In [16]:
CXH = tensor((iid - sigz) , (iid - sigx))
CX = (-np.pi * 0.25 *  1j *CXH).expm()

In [17]:
CX

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.46630142e-17  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  6.32520476e-17]]

In [20]:
# nosie ver
cx_std = 0.065
(CXH * normal(np.pi * 0.25 , cx_std) * -1j).expm()

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j        ]
 [0.       +0.j         1.       +0.j         0.       +0.j
  0.       +0.j        ]
 [0.       +0.j         0.       +0.j         0.0145645+0.11980141j
  0.9854355-0.11980141j]
 [0.       +0.j         0.       +0.j         0.9854355-0.11980141j
  0.0145645+0.11980141j]]