In [1]:
import qutip
from qutip import Qobj,basis
from qutip import sigmax , sigmaz , sigmay
from qutip import tensor
from numpy.random import normal
import numpy as np

In [2]:
sigx = sigmax()
sigz = sigmaz()
sigy = sigmay()
iid = qutip.qeye(2)

In [3]:
CXH = tensor((iid - sigz) , (iid - sigx))
CX = (-np.pi * 0.25 *  1j *CXH).expm()

In [4]:
CX

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.46630142e-17  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  9.41330427e-17]]

In [ ]:
# nosie ver
cx_std = 0.065
(CXH * normal(np.pi * 0.25 , cx_std) * -1j).expm()